name: cpp_linter

on: [push, pull_request]

jobs:
  cpp_linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compiler: gcc
            build_type: Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: OpenCV cache
        id: opencv-cache
        uses: actions/cache@v4
        with:
          path: ./libs/opencv_install
          key: ${{ runner.os }}-opencv-cache-v2

      - name: ONNX cache
        id: onnxruntime-cache
        uses: actions/cache@v4
        with:
          path: ./libs/onnxruntime_install
          key: ${{ runner.os }}-onnxruntime-cache-v2

      - name: Configure
        run: |
          sudo python -u build.py --ci --compiler ${{ matrix.compiler }} --build_type ${{ matrix.build_type }} --configure_only
          ls -la build

      - name: Install Dependencies
        run: sudo apt-get install -y clang-format clang-tidy

      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          database: '${{ github.workspace }}/build'
          ignore: 'libs'
          jobs: 0
          style: file # use .clang-format file
          tidy-checks: '' # use .clang-tidy file
          files-changed-only: true
          file-annotations: true # In the "Files Changed" tab (Inline Code Annotations)
          thread-comments: false # Posts a summary comment on the PR
          step-summary: true # Shows a markdown summary on the Action run page
          tidy-review: true # In the "Conversation" tab (Review Style)
          format-review: true # In the "Conversation" tab (Review Style)

      - name: Fail if checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
